### ISSUE TITLE
Custom Scroll Locations?

### ISSUE THREAD

**Issue by krishaamer** [tomyo/flow-router-autoscroll#1]
Hey @tomyo, thanks for your work! 

Is it possible to scroll to Top of the page or to a specific # location in the middle of the page?

Best,
Kris

**Comment by tomyo** [comment]
Hi Kris!  You're welcome.
1. To top, yes, unless routs is in except list.
2. To element Id (# location), it should work, but only if that element is
present when rendering the route content. Usually that element is rendered
when subscriptions are ready, in that case, you need call the scroll
function manually. No big deal though, just look at the code, is quite
simple.

Hope it helps!

**Comment by tomyo** [comment]
Hi Kris!  You're welcome.
1. To top, yes, unless routes is in except list.
2. To element Id (# location), it should work, but only if that element is
present when rendering the route content. If that element is rendered
when subscriptions are ready, you'll need call the scroll
function manually. Here's an example of how I accomplish that in my code, in a section where I have tabs:

```
if @currentTab() != 'following'
    headerHeightCompensation = 45
    pos = $("##{@currentTab()}").offset().top - headerHeightCompensation
    # Scroll to tab content
    $('body, html').animate({scrollTop: pos});
```

Hope it helps!
